### ISSUE TITLE
Create CSV for former team members

### ISSUE THREAD

**Issue by ledell** [rladies/starter-kit#215]
We currently have a [CSV](https://github.com/rladies/starter-kit/blob/master/global-team.csv) which includes everyone who currently is part of the global team and also people who are no longer affiliated with R-Ladies.  Let's break this out into two CSVs: global-team.csv and former-global-team.csv or global-team-alumni.csv

**Comment by maelle** [comment]
why two csv?
btw for the website would a JSON be easier? cc @Athanasiamo

**Comment by Athanasiamo** [comment]
It ended up in two because the "former" list would over time likely be long, and we thought it convenient to have a dedicated file for current members (for others, not necessarily our selves).

and csv because I think the four of us working on this are just used to working with table'd data, so it was easy to make.

**Comment by maelle** [comment]
ok, and where is that file used from? Is it used from Hugo too?

**Comment by Athanasiamo** [comment]
They are both used in the new blogdown "Meet the global team" page.

**Comment by maelle** [comment]
thanks! 

also, is there any remaining work or can this issue be closed?

**Comment by Athanasiamo** [comment]
No, my PR was merged by Yanina ( #217 ) so should be ok now
